services:
  frontend:
    container_name: frontend
    build: ./frontend/
    image: frontend
    restart: on-failure
    depends_on:
      - backend
    env_file: .env
    ports:
      - '3000:3000'
  backend:
    container_name:  backend
    build: ./backend/
    image: backend
    restart: on-failure
    env_file: .env
    depends_on:
      - postgres
    ports:
      - '3001:3001'
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    restart: on-failure
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "5050:80"
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    env_file: .env
    build: ./postgres/
    restart: on-failure
    ports:
      - '5432:5432'
